// This file is @generated by prost-build.
/// The request message containing data to encode in qr code.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QrCodeRequest {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub size: i32,
    #[prost(enumeration = "Format", tag = "3")]
    pub format: i32,
    #[prost(message, optional, tag = "4")]
    pub bg_color: ::core::option::Option<Rgba>,
    #[prost(message, optional, tag = "5")]
    pub logo_bg_color: ::core::option::Option<Rgba>,
    #[prost(oneof = "qr_code_request::Logo", tags = "6, 7, 8")]
    pub logo: ::core::option::Option<qr_code_request::Logo>,
}
/// Nested message and enum types in `QrCodeRequest`.
pub mod qr_code_request {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Logo {
        #[prost(enumeration = "super::PredefinedLogo", tag = "6")]
        PredefinedLogo(i32),
        #[prost(bytes, tag = "7")]
        Image(::prost::alloc::vec::Vec<u8>),
        #[prost(string, tag = "8")]
        ImageUrl(::prost::alloc::string::String),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QrCodeResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub qr_code: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rgba {
    #[prost(uint32, tag = "1")]
    pub r: u32,
    #[prost(uint32, tag = "2")]
    pub g: u32,
    #[prost(uint32, tag = "3")]
    pub b: u32,
    #[prost(uint32, tag = "4")]
    pub a: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Format {
    Png = 0,
    Jpeg = 1,
    Svg = 2,
}
impl Format {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Format::Png => "PNG",
            Format::Jpeg => "JPEG",
            Format::Svg => "SVG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PNG" => Some(Self::Png),
            "JPEG" => Some(Self::Jpeg),
            "SVG" => Some(Self::Svg),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PredefinedLogo {
    Google = 0,
    Facebook = 1,
    Twitter = 2,
    Instagram = 3,
    Youtube = 4,
    Linkedin = 5,
    Github = 6,
    Tiktok = 7,
    Snapchat = 8,
    Pinterest = 9,
    Reddit = 10,
    Discord = 11,
    Zoom = 12,
    Slack = 13,
}
impl PredefinedLogo {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            PredefinedLogo::Google => "GOOGLE",
            PredefinedLogo::Facebook => "FACEBOOK",
            PredefinedLogo::Twitter => "TWITTER",
            PredefinedLogo::Instagram => "INSTAGRAM",
            PredefinedLogo::Youtube => "YOUTUBE",
            PredefinedLogo::Linkedin => "LINKEDIN",
            PredefinedLogo::Github => "GITHUB",
            PredefinedLogo::Tiktok => "TIKTOK",
            PredefinedLogo::Snapchat => "SNAPCHAT",
            PredefinedLogo::Pinterest => "PINTEREST",
            PredefinedLogo::Reddit => "REDDIT",
            PredefinedLogo::Discord => "DISCORD",
            PredefinedLogo::Zoom => "ZOOM",
            PredefinedLogo::Slack => "SLACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GOOGLE" => Some(Self::Google),
            "FACEBOOK" => Some(Self::Facebook),
            "TWITTER" => Some(Self::Twitter),
            "INSTAGRAM" => Some(Self::Instagram),
            "YOUTUBE" => Some(Self::Youtube),
            "LINKEDIN" => Some(Self::Linkedin),
            "GITHUB" => Some(Self::Github),
            "TIKTOK" => Some(Self::Tiktok),
            "SNAPCHAT" => Some(Self::Snapchat),
            "PINTEREST" => Some(Self::Pinterest),
            "REDDIT" => Some(Self::Reddit),
            "DISCORD" => Some(Self::Discord),
            "ZOOM" => Some(Self::Zoom),
            "SLACK" => Some(Self::Slack),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod qr_generator_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with QrGeneratorServer.
    #[async_trait]
    pub trait QrGenerator: Send + Sync + 'static {
        async fn generate_qr_code(
            &self,
            request: tonic::Request<super::QrCodeRequest>,
        ) -> std::result::Result<tonic::Response<super::QrCodeResponse>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct QrGeneratorServer<T: QrGenerator> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: QrGenerator> QrGeneratorServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
            where
                F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for QrGeneratorServer<T>
        where
            T: QrGenerator,
            B: Body + Send + 'static,
            B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/QrGenerator/GenerateQrCode" => {
                    #[allow(non_camel_case_types)]
                    struct GenerateQrCodeSvc<T: QrGenerator>(pub Arc<T>);
                    impl<
                        T: QrGenerator,
                    > tonic::server::UnaryService<super::QrCodeRequest>
                    for GenerateQrCodeSvc<T> {
                        type Response = super::QrCodeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QrCodeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as QrGenerator>::generate_qr_code(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GenerateQrCodeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: QrGenerator> Clone for QrGeneratorServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: QrGenerator> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: QrGenerator> tonic::server::NamedService for QrGeneratorServer<T> {
        const NAME: &'static str = "QrGenerator";
    }
}
