// Code generated by goctl. DO NOT EDIT.
// Source: id_gen.proto

package server

import (
	"context"

	"id_generator/service/id_generator"
	"id_generator/service/internal/logic"
	"id_generator/service/internal/svc"
)

type IdGeneratorServer struct {
	svcCtx *svc.ServiceContext
	id_generator.UnimplementedIdGeneratorServer
}

func NewIdGeneratorServer(svcCtx *svc.ServiceContext) *IdGeneratorServer {
	return &IdGeneratorServer{
		svcCtx: svcCtx,
	}
}

func (s *IdGeneratorServer) GenId(ctx context.Context, in *id_generator.IdGenRequest) (*id_generator.IdGenResponse, error) {
	l := logic.NewGenIdLogic(ctx, s.svcCtx)
	return l.GenId(in)
}
